[versions]
agp = "8.1.1"
org-jetbrains-kotlin-android = "1.9.0"
core-ktx = "1.9.0"
recyclerview = "1.3.1"
appcompat = "1.6.1"
okHttp = "4.11.0"
commons-io = "2.13.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-recycler = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
okHttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }

[bundles]

